import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm';
const db = createClient('https://jbcxodpudujoscdafovx.supabase.co', "sb_publishable_ZZvmnAgd81ui0_PkzopkaQ_-hGz88v_");
const $ = id => document.getElementById(id);
let user=null,selectedEvent=null,attendance='attending';
const status = text => { $('account-status').textContent=text; };
async function profile(){
 const display=user.user_metadata?.display_name||user.email.split('@')[0];
 const {error}=await db.from('profiles').upsert({id:user.id,display_name:display}); if(error)throw error;
 if(user.user_metadata?.account_kind==='creator') {const {error}=await db.from('event_creators').upsert({user_id:user.id,organizer_name:display});if(error)throw error;}
}
async function myEvents(){
 $('my-events').replaceChildren();if(!user)return;
 const {data,error}=await db.from('events').select('id,title,hashtag,starts_at').eq('creator_id',user.id).order('created_at',{ascending:false});if(error)throw error;
 if(data.length){const heading=document.createElement('h3');heading.textContent='Your saved events';heading.className='font-bold';$('my-events').append(heading);}
 for(const event of data){const row=document.createElement('p');row.textContent=event.title+' — #'+event.hashtag+' — '+new Date(event.starts_at).toLocaleString();$('my-events').append(row);}
}
async function sync(session){user=session?.user||null;$('account-form').hidden=!!user;$('account-signed-in').hidden=!user;if(user){$('account-user').textContent='Signed in as '+user.email;try{await profile();await myEvents();status('Your account is connected.');}catch(e){status(e.message);}}else{$('my-events').replaceChildren();status('Sign in to save your profile, RSVP, or event.');}}
$('account-form').addEventListener('submit',async e=>{e.preventDefault();status('Signing in…');const {data,error}=await db.auth.signInWithPassword({email:$('account-email').value.trim(),password:$('account-password').value});if(error){status(error.message);return;}$('account-password').value='';await sync(data.session);});
$('account-signup').addEventListener('click',async()=>{if(!$('account-form').reportValidity())return;const name=$('account-name').value.trim();if(!name){status('Enter your name to create an account.');return;}status('Creating account…');const {data,error}=await db.auth.signUp({email:$('account-email').value.trim(),password:$('account-password').value,options:{emailRedirectTo:'https://www.unabl.app/',data:{display_name:name,account_kind:$('account-kind').value}}});if(error){status(error.message);return;}$('account-password').value='';if(data.session)await sync(data.session);else status('Check your email to confirm your account, then sign in here.');});
$('account-signout').addEventListener('click',async()=>{const {error}=await db.auth.signOut();if(error)status(error.message);else await sync(null);});
const oldRSVP=window.setRSVP;window.setRSVP=type=>{attendance=type;oldRSVP(type);};
window.saveEvent=async()=>{if(!user){status('Sign in or create an event creator account first.');$('account-email').focus();return;}const title=$('event-title-input').value.trim(),hashtag=$('newHashtagInput').value.trim().replace(/^#/,'').toLowerCase(),venue=$('event-venue').value.trim(),start=$('event-starts').value;if(!title||!venue||!start||!(/^[a-z0-9_]{3,60}$/).test(hashtag)){status('Enter an event title, venue, date/time, and a hashtag with 3–60 letters, numbers, or underscores.');return;}const button=$('event-save');button.disabled=true;try{const {data:creator,error:ce}=await db.from('event_creators').select('user_id').eq('user_id',user.id).maybeSingle();if(ce)throw ce;if(!creator)throw Error('This account is a guest account. Create an event creator account to publish events.');const {error}=await db.from('events').insert({creator_id:user.id,title,category:$('eventCatInput').value,hashtag,starts_at:new Date(start).toISOString(),venue,published:true});if(error)throw error;status('Event published. Share the hashtag #'+hashtag+'.');await myEvents();}catch(e){status(e.code==='23505'?'That hashtag is already in use. Choose another.':e.message);}finally{button.disabled=false;}};
window.searchEvent=async()=>{const tag=$('searchHashtag').value.trim().replace(/^#/,'').toLowerCase();if(!tag)return;const {data,error}=await db.from('events').select('id,title,hashtag,category,starts_at,venue').eq('hashtag',tag).eq('published',true).maybeSingle();if(error){$('event-status').textContent=error.message;return;}if(!data){selectedEvent=null;$('event-status').textContent='No published event found with that hashtag.';return;}selectedEvent=data;$('eventTitle').textContent=data.title;$('displayHashtag').textContent='#'+data.hashtag;$('eventCategory').textContent=data.category;$('event-status').textContent=new Date(data.starts_at).toLocaleString()+' · '+data.venue;};
$('rsvp-save').addEventListener('click',async()=>{if(!user){$('event-status').textContent='Sign in to save your RSVP.';return;}if(!selectedEvent){$('event-status').textContent='Find a published event by hashtag first.';return;}const {error}=await db.from('event_responses').upsert({event_id:selectedEvent.id,user_id:user.id,attendance,message:$('guestMessage').value.trim()},{onConflict:'event_id,user_id'});$('event-status').textContent=error?error.message:'Your RSVP and message were saved. No payment has been collected.';});
db.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>sync(session),0);});
const {data,error}=await db.auth.getSession();if(error)status(error.message);else await sync(data.session);
